RUN bash <(curl -s https://raw.githubusercontent.com/mylinuxforwork/dotfiles/main/share/packages/fedora/special/gum.sh) && \
    git clone --branch $(curl --silent "https://api.github.com/repos/mylinuxforwork/dotfiles/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/') --depth 1 https://github.com/mylinuxforwork/dotfiles.git /tmp/dotfiles && \
    cd /tmp/dotfiles/bin/ && \
    mkdir -p /usr/local/{bin,share,lib} && \
    cp /tmp/dotfiles/bin/ml4w-hyprland-setup /usr/local/bin/ml4w-hyprland-setup && \
    cp -ar /tmp/dotfiles/share/. /usr/local/share && \
    cp -ar /tmp/dotfiles/lib/. /usr/local/lib && \
    dnf install -y figlet && \
    dnf clean all && \
    rm -rf /tmp/dotfiles

